# Generated by Django 2.0.4 on 2018-04-15 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.BooleanField(default=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=4, null=True)),
                ('outside_shape', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('base_type', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('height_over_tube', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=6, null=True)),
                ('bolt_pattern_long', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('bolt_pattern_wide', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('groove', models.BooleanField(default=False)),
                ('base_diameter', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('shoulder_diameter', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True)),
                ('unique_feature', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type_name', models.CharField(blank=True, default=None, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(blank=True, default=None, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_date', models.DateField()),
                ('annual_usage', models.IntegerField(blank=True, default=None, null=True)),
                ('bracket_pricing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PriceQuoteSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=20, max_digits=30)),
                ('min_order_quantity', models.IntegerField(default=1)),
                ('price_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.PriceQuote')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TubeAssembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TubeAssemblyComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('component', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industria.Component')),
                ('tube_assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.TubeAssembly')),
            ],
        ),
        migrations.AddField(
            model_name='pricequotesupplier',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.Supplier'),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='price_quote_supplier',
            field=models.ManyToManyField(through='industria.PriceQuoteSupplier', to='industria.Supplier'),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='tube_assembly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industria.TubeAssembly'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industria.ComponentType'),
        ),
        migrations.AddField(
            model_name='component',
            name='connection_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='industria.ConnectionType'),
        ),
    ]
